"""Prepare a trip's photos for the journal.

    python tools/prepare_images.py huai-nam-yen

Run it after adding, replacing or removing photos in trips/<slug>/. It:
  * shrinks very large photos (longest edge > 1800px) in place and removes EXIF,
    including GPS location, so nothing private is published;
  * converts DNG files to JPG next to them when `rawpy` is installed;
  * writes smaller copies to trips/<slug>/_sized/<500|1000>/ for phones;
  * writes trips/<slug>/images.js with every photo's width and height, so the
    page reserves the right space before each photo loads.

Needs Pillow:  pip install pillow   (and optionally  pip install rawpy  for DNG)
"""
import sys
from pathlib import Path

try:
    from PIL import Image, ImageOps
except ImportError:
    sys.exit("Pillow is missing. Install it with:  pip install pillow")

MAX_EDGE = 1800
VARIANTS = (500, 1000)          # keep in sync with VARIANTS in assets/journal-images.js
PHOTO_EXT = {".jpg", ".jpeg", ".png", ".webp"}
ROOT = Path(__file__).resolve().parent.parent


def save(im, path, fmt):
    if fmt == "JPEG":
        im.convert("RGB").save(path, "JPEG", quality=82, optimize=True, progressive=True)
    else:
        im.save(path, fmt, optimize=True)


def convert_raw(path):
    try:
        import rawpy
    except ImportError:
        print(f"  skip {path.name}: DNG needs `pip install rawpy`, or export it as JPG")
        return None
    out = path.with_suffix(".jpg")
    if out.exists():
        return None
    with rawpy.imread(str(path)) as raw:
        Image.fromarray(raw.postprocess(use_camera_wb=True, output_bps=8)).save(out, "JPEG", quality=92)
    print(f"  converted {path.name} -> {out.name} (you can delete the .dng; it is not published)")
    return out


def main(slug):
    trip = ROOT / "trips" / slug
    if not trip.is_dir():
        sys.exit(f"No folder trips/{slug}/")
    sized = trip / "_sized"

    for raw in [p for p in trip.rglob("*") if p.suffix.lower() == ".dng" and sized not in p.parents]:
        convert_raw(raw)

    photos = sorted(p for p in trip.rglob("*") if p.suffix.lower() in PHOTO_EXT and sized not in p.parents)
    manifest, wanted = {}, set()
    for path in photos:
        rel = path.relative_to(trip).as_posix()
        im = Image.open(path)
        fmt = im.format
        has_exif = bool(im.getexif())
        im = ImageOps.exif_transpose(im)
        if max(im.size) > MAX_EDGE or has_exif:
            im.thumbnail((MAX_EDGE, MAX_EDGE), Image.LANCZOS)
            save(im, path, fmt)
            print(f"  optimized {rel} -> {im.size[0]}x{im.size[1]}, metadata removed")
        w, h = im.size
        manifest[rel] = [w, h]
        for edge in VARIANTS:
            if max(w, h) <= edge * 1.15:
                continue
            out = sized / str(edge) / rel
            wanted.add(out)
            if out.exists() and out.stat().st_mtime >= path.stat().st_mtime:
                continue
            out.parent.mkdir(parents=True, exist_ok=True)
            small = im.copy()
            small.thumbnail((edge, edge), Image.LANCZOS)
            save(small, out, fmt)

    for old in [p for p in sized.rglob("*") if p.is_file() and p not in wanted] if sized.exists() else []:
        old.unlink()
        print(f"  removed stale {old.relative_to(trip).as_posix()}")

    lines = [f'  "{k}": [{w}, {h}]' for k, (w, h) in manifest.items()]
    (trip / "images.js").write_text(
        "// Generated by tools/prepare_images.py — do not edit by hand.\n"
        "(window.JOURNAL_IMAGE_SIZES = window.JOURNAL_IMAGE_SIZES || {})"
        f'["{slug}"] = {{\n' + ",\n".join(lines) + "\n};\n",
        encoding="utf-8",
    )
    print(f"{len(manifest)} photos ready in trips/{slug}/ (images.js updated)")


if __name__ == "__main__":
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
